### ISSUE TITLE
Locale should be added automatically to menu links

### ISSUE THREAD

**Issue by iwazaru** [elytre/elytre#108]
Currently a link in a must include locale:

```yaml
  nav:
    - label: Livres
      href: /fr/pages/livres
```

User should not have to include locale, as it should be automatically added based on currently selected locale:

```yaml
  nav:
    - label: Livres
      href: /pages/livres
```
