### ISSUE TITLE
Add header menu and footer menu options to site config 

### ISSUE THREAD

**Issue by iwazaru** [elytre/elytre#98]
```yaml
header:
  menu:
  - label : About
     link: /pages/about
  - label: contact
     link: /contact/
```
